trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: frontend-staticapp-token  # Link your variable group here

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: AzureStaticWebApp@0
  displayName: 'Deploy to Azure Static Web Apps'
  inputs:
    app_location: '/'
    output_location: 'build'
    azure_static_web_apps_api_token: $(deployment_token)
